[package]
name = "nu_plugin_file"
version = "0.6.0"
authors = ["Darren Schroeder", "glcraft"]
edition = "2021"
repository = "https://github.com/fdncred/nu_plugin_file"
description = "a nushell plugin called file"
license = "AGPL-3.0-only"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# nushell dependencies
nu-plugin = "0.97.1"
nu-protocol = "0.97.1"
nu-path = "0.97.1"

# for local development, you can use a path dependency
# nu-plugin = { path = "../nushell/crates/nu-plugin", version = "0.97.2" }
# nu-protocol = { path = "../nushell/crates/nu-protocol", version = "0.97.2" }
# nu-path = { path = "../nushell/crates/nu-path", version = "0.97.2" }

serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
strum = { version = "0.26.3", features = ["derive"] }
strum_macros = "0.26.4"
specta = "1.0.5"
home = "0.5.9"
itertools = "0.13.0"
goblin = { version = "0.8.2", optional = true }

[features]
default = ["executables"]
executables = ["goblin"]
